### ISSUE TITLE
ValueError during script execution with conflicting generation settings

### ISSUE THREAD

**Issue by chenzhi-cz** [Dynamite321/CodeGuardPlus#1]
Hello,

When I execute the command `bash eval.sh Salesforce/codegen-2B-multi codegen2b-cbs base cbs`, I encounter the following error:

> ValueError: one of `constraints`, `force_words_ids` is not `None`, triggering constrained beam search. However, `do_sample` is set to `True`, which is incompatible with this generation mode. Set `constraints` and `force_words_ids` to `None` or unset `do_sample` to continue.

Here is the related code:
```
# Running generation
echo "Running generation using $DECODING decoding."
COMMAND="python generate.py --model_type lm --model_dir $MODEL_DIR --output_name $OUTPUT_NAME --eval_type $EVAL_TYPE"
case "$DECODING" in
    nucleus)
        COMMAND+=" --do_sample --num_gen 10"
        ;;
    beam)
        COMMAND+=" --do_sample --num_beams 25 --num_gen 10"
        ;;
    cbs)
        COMMAND+=" --do_sample --num_beams 25 --num_gen 10 --use_pos_constraints --use_neg_constraints"
        ;;
    *)
        echo "Invalid DECODING method specified."
        continue
        ;;
esac
```
Should `constraints` and `force_words_ids` be adjusted, or should `do_sample` be disabled? Any guidance or workaround would be greatly appreciated.

Thank you :)

**Comment by Dynamite321** [comment]
Thank you for your interest in our work! I implement constrained beam sampling (CBS) via customizing the Huggingface transformers. I haven't uploaded my customized version of transformers to this repo, so you will encounter problems while running CBS. You may either wait for my updates or email me (see the benchmark website for my email) for my uncleaned, customized version of transformers and install it from the source. Sorry for the inconvenience! By the way, I have begun to migrate this repo from my account to an official one, https://github.com/CodeGuardPlus/CodeGuardPlus. All new updates will be first made in the official repo.

**Comment by chenzhi-cz** [comment]
Thank you for your reply. I will keep an eye on your official project repository and look forward to your updates. It looks like a very good project ：）
